whisk/config/routes.rb
Rails.application.routes.draw do
  # get 'reviews/index'
  #
  # get 'reviews/show'
  #
  # get 'reviews/new'
  #
  # get 'reviews/create'
  #
  # get 'reviews/edit'
  #
  # get 'reviews/update'
  #
  # get 'reviews/destroy'
  #
  get 'users/index'

  get 'users/show'

  get 'users/edit'

  devise_for :users
  root to: 'desserts#index'

  resources :desserts do
    resources :recipes do
      resources :reviews
    end
  end

  resources :recipes, only: [:index, :show] do
    member do
      post 'add_favorite'
      delete 'remove_favorite'
    end
  end
  # get 'recipes/index'
  #
  # get 'recipes/new'
  #
  # get 'recipes/create'
  #
  # get 'recipes/show'
  #
  # get 'recipes/edit'
  #
  # get 'recipes/update'
  #
  # get 'recipes/destroy'
  #
  # get 'desserts/index'
  #
  # get 'desserts/new'
  #
  # get 'desserts/create'
  #
  # get 'desserts/show'
  #
  # get 'desserts/edit'
  #
  # get 'desserts/update'
  #
  # get 'desserts/destroy'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

whisk/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

whisk/app/models/dessert.rb
class Dessert < ApplicationRecord
  has_many :recipes, dependent: :destroy
  validates :name, :dessert_image, presence: true
end

whisk/app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

whisk/app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :dessert
  belongs_to :user

  has_many :favorites
  has_many :reviews
  has_many :users, through: :favorites

  validates :name, :description, :ingredients, :direction, :preptime, :cooktime, :recipe_image, presence: true
end

whisk/app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  validates :body, presence: true
end

whisk/app/models/user.rb
class User < ApplicationRecord
  has_many :favorites
  has_many :reviews
  has_many :recipes, through: :favorites
  has_many :user_recipes, foreign_key: "user_id", class_name: "Recipe"
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, :email, :password, presence: true

end

whisk/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  rescue_from ActiveRecord::RecordNotFound, with: :couldnt_find_record
  rescue_from NoMethodError, with: :no_method_error


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  private
  def couldnt_find_record
    redirect_to root_url, notice: "That record doesn't exist!"
  end

  def no_method_error
    redirect_to root_url, notice: "The page doesn't exist!"
  end
end

whisk/app/controllers/desserts_controller.rb
class DessertsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
      @desserts = Dessert.all
    end

    def show
      @dessert = Dessert.find(params[:id])
    end

    def new
      @dessert = Dessert.new
    end

    def create
      @dessert = Dessert.create(dessert_params)
      redirect_to desserts_path, notice: "You created a new #{@dessert.name}."

    end

    def edit
      @dessert = Dessert.find(params[:id])
    end

    def update
      @dessert = Dessert.find(params[:id])
      @dessert.update(dessert_params)
      redirect_to dessert_path(@dessert), notice: "You updated #{@dessert.name}."

    end

    def destroy
      @dessert = Dessert.find(params[:id])
      @dessert.destroy
      redirect_to desserts_path, notice: "You deleted #{@dessert.name}."

    end

    private
    def dessert_params
      params.require(:dessert).permit(:name, :dessert_image)
    end
end

whisk/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def add_favorite
    @recipe = Recipe.find(params[:id])
    @recipe.favorites.create(user: current_user)
    redirect_to dessert_recipe_path(@recipe.dessert_id, @recipe), notice: "You added #{@recipe.name} to your favorite!"

  end

  def remove_favorite
    @recipe = Recipe.find(params[:id])
    @favorite = Favorite.find_by(user: current_user, recipe_id: params[:id])
    @favorite.destroy
    redirect_to dessert_recipe_path(@recipe.dessert_id, @recipe), notice: "You removed #{@recipe.name} from your favorite!"
  end

  def index
    @recipes = Recipe.all
  end


  def show
    @recipe = Recipe.find(params[:id])
  end


  def new
    @dessert = Dessert.find(params[:dessert_id])
    @recipe = @dessert.recipes.new
  end


  def create
    @dessert = Dessert.find(params[:dessert_id])
    @recipe = @dessert.recipes.create!(recipe_params.merge(user: current_user, ingredients: params[:recipe][:ingredients].split(",")))
    redirect_to dessert_path(@dessert), notice: "You added a new recipe to #{@dessert.name}."
  end


  def edit
    @dessert = Dessert.find(params[:dessert_id])
    @recipe = Recipe.find(params[:id])

  end


  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.user == current_user
      @recipe.update!(recipe_params.merge(user: current_user, ingredients: params[:recipe][:ingredients].split(",")))
    else
      flash[:alert] = "You can't update this!"
    end
    redirect_to dessert_recipe_path(@recipe.dessert_id, @recipe), notice: "You updated #{@recipe.name}."
  end


  def destroy
    @recipe = Recipe.find(params[:id])
    if @recipe.user == current_user
    @recipe.destroy
  else
    flash[:alert] = "You can't delete this!"
  end
    redirect_to dessert_path(@recipe.dessert_id), alert: "You deleted #{@recipe.name}!"
  end

  private
  def recipe_params
    params.require(:recipe).permit(:name, :description, :ingredients, :direction, :preptime, :cooktime, :recipe_image)
  end
end

whisk/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end

  def show
    @review = Review.find(params[:id])
  end

  def new
    @dessert = Dessert.find(params[:dessert_id])
    @recipe = Recipe.find(params[:recipe_id])
    @review = Review.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @review = @recipe.reviews.create!(review_params.merge(user: current_user))
    redirect_to dessert_recipe_path(@recipe.dessert_id, @recipe), notice: "You added a new comment."
  end

  def edit
    @dessert = Dessert.find(params[:dessert_id])
    @recipe = Recipe.find(params[:recipe_id])
    @review = Review.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:recipe_id])
    @review = Review.find(params[:id])
    if @review.user == current_user
      @review.update!(review_params)
    else
      flash[:alert] = "You can't update this!"
    end
    redirect_to dessert_recipe_path(@recipe.dessert_id, @recipe), notice: "You updated your comment."
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @review = Review.find(params[:id])
    if @review.user == current_user
      @review.destroy
    else
      flash[:alert] = "You can't delete this!"
    end
    redirect_to dessert_recipe_path(@recipe.dessert_id, @recipe), alert: "You deleted your comment."
  end

  private
  def review_params
    params.require(:review).permit(:body)
  end
end

whisk/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipe = Recipe.where(user_id: current_user)
    @favorite = Favorite.where(user_id: current_user)
  end

end

whisk/app/helpers/application_helper.rb
module ApplicationHelper
end

whisk/app/helpers/desserts_helper.rb
module DessertsHelper
end

whisk/app/helpers/recipes_helper.rb
module RecipesHelper
end

whisk/app/helpers/reviews_helper.rb
module ReviewsHelper
end

whisk/app/helpers/users_helper.rb
module UsersHelper
end

whisk/app/views/desserts/_form.html.erb
<%= form_for @dessert do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :dessert_image %>
  <%= f.text_field :dessert_image %>

  <%= f.submit %>

<% end %>

whisk/app/views/desserts/edit.html.erb
<h2>Edit Dessert</h2>


<%= render 'form' %>

<%= link_to 'Delete!', dessert_path(@dessert), method: :delete, class: 'delete' %>

whisk/app/views/desserts/index.html.erb
<div class="container marketing">
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec condimentum ligula ut felis auctor vestibulum. Proin in leo ullamcorper, tempor eros eu, suscipit nisi. Suspendisse massa nulla, condimentum sed libero sed, dignissim dictum sapien. Quisque molestie dui enim, at egestas sapien sodales in. Fusce vehicula arcu at sodales consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec condimentum ligula ut felis auctor vestibulum. Proin in leo ullamcorper, tempor eros eu, suscipit nisi. Condimentum sed libero sed, dignissim dictum sapien. Quisque molestie dui enim, at egestas sapien sodales in. Fusce vehicula arcu at sodales consequat.</p>
  <br>

  <hr class="style_no_symbol">
  <h1 class="index_h1">Recipes by Category</h1>
  <hr class="style">
  <br>
  <br>
  <% @desserts.each do |dessert| %>
    <div class="col-lg-4">
      <a href="/desserts/<%=dessert.id%>"><img class="img-circle" alt="desserts" src="<%= dessert.dessert_image %>"></a>
      <a href="/desserts/<%=dessert.id%>"><h2><%= dessert.name %></h2></a>
    </div>
  <%end%>
</div>

whisk/app/views/desserts/new.html.erb
<h2>New Dessert</h2>

<%= render 'form' %>

whisk/app/views/desserts/show.html.erb
<div class="links">
  <hr class="style_no_symbol">
  <h1 class="index_h1"><%= @dessert.name %></h1>
  <% if current_user %>
  <ul>
<li>&#8212<%= link_to "Add Recipe", new_dessert_recipe_path(@dessert) %>&#8212</li>
  </ul>


</div>
<%end%>
<hr class="style">

<br>
<br>

<div class="dessert_show_wrapper">
<div class="dessert_show_recipes">
<% @dessert.recipes.each do |recipe| %>
  <div class="dessert_show_recipe_wrapper">
  <a href="/desserts/<%=recipe.dessert_id%>/recipes/<%=recipe.id%>"><img class="dessert_show_recipe" src="<%= recipe.recipe_image %>"></a>
  <h4><%= link_to recipe.name, dessert_recipe_path(@dessert, recipe) %></h4>
</div>
<%end%>
</div>
</div>

whisk/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Whisk | Sugar, Spice & Everything Nice!</title>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Dosis:300,400,500,700" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>
  <header>
    <div class="wrapper">
      <div class="navbar-wrapper">
        <div class="container">
          <nav class="navbar navbar-inverse navbar-static-top">
            <div class="container">

              <div class="navbar-header">
                <a class="navbar-brand" style="color: white" href="/">Whisk!</a>
              </div>

              <div>
                <ul class="nav navbar-nav">
                  <li ><%= link_to "Recipes", desserts_path %></li>
                  <% if current_user %>
                  <li><%= link_to 'Signout', destroy_user_session_path, :method => :delete %></li>
                  <li><%= link_to "My Profile", users_index_path %></li>
                  <% else %>
                  <li><%= link_to 'Signup', new_user_registration_path %></li>
                  <li><%= link_to 'Login', new_user_session_path %></li>
                  <% end %>
                </ul>
              </div>

            </div>
          </nav>
        </div>
        <h1 style="font-family:'Pacifico', cursive; color: white; text-align: center; font-size: 70px; margin-top: 80px;">Sugar & Spice</h1>
      </div>
    </div>
    </header>
    <div class="container marketing">



              <p class="notice"><%= notice %></p>
              <p class="alert"><%= alert %></p>
              <%= yield %>
          </div><!-- /.row -->




<main>

</main>
  </body>
  </html>

whisk/app/views/recipes/_form.html.erb
<div class="form">
<%= form_for [@dessert, @recipe] do |f| %>

  <div class="form_left">
  <div>
  <%= f.label :name %>
  <br>
  <%= f.text_area :name, size: "70x1" %>
</div>

  <div>
  <%= f.label :description %>
  <br>
  <%= f.text_area :description, size: "70x6" %>
  </div>
  <br>

  <div>
  <%= f.label :preptime %> (minutes)
  <br>
  <%= f.text_field :preptime %>
  </div>
  <br>

  <div>
  <%= f.label :cooktime %> (minutes)
  <br>
  <%= f.text_field :cooktime %>
  </div>
  <br>
</div>

<div class="form_right">
  <div>
  <%= f.label :ingredients %> - Separate each ingredients by commas.
  <br>
  <%= f.text_area :ingredients, size: "100x10" %>
  </div>
  <br>

  <div>
  <%= f.label :direction %>
  <br>
  <%= f.text_area :direction, size: "100x10" %>
  </div>
  <br>



  <div>
  <%= f.label :recipe_image %>
  <br>
  <%= f.text_field :recipe_image, size: "100x1"  %>
  </div>
  <br>


  <%= f.submit %>

</div>

<% end %>
</div>

whisk/app/views/recipes/edit.html.erb
<h2>Edit <%= @recipe.name  %> </h2>

<div class="edit-form">
  <%= render "form"  %>
</div>

whisk/app/views/recipes/index.html.erb
<h2>All recipes</h2>

whisk/app/views/recipes/new.html.erb
<h2>New Recipe</h2>

<%= render 'form' %>

whisk/app/views/recipes/show.html.erb
<div class="links">

<% if @recipe.user == current_user %>
<hr class="style_no_symbol">
<ul>
  <li>&#8212<%= link_to "Edit Recipe", edit_dessert_recipe_path(@recipe.dessert_id, @recipe) %>&#8212</li>
  <li>&#8212<%= link_to "Delete Recipe", dessert_recipe_path(@recipe), :method => :delete %>&#8212</li>
</ul>
<hr class="style">
<%else%>
<%end%>
</div>

<br>
<br>


<div class="recipe_wrapper">
  <div class="recipe_description">
  <h1><%=@recipe.name%>
    <% if @recipe.users.include? current_user %>
    <%= link_to "&hearts;".html_safe, remove_favorite_recipe_path(@recipe), method: :delete, class: "fav" %>
    <% else %>
    <%= link_to "&hearts;".html_safe, add_favorite_recipe_path(@recipe), method: :post, class: "no-fav" %>
    <% end %>
  </h1>
  <h4>Recipe by: <%= @recipe.user.username %>&nbsp; | &nbsp; <%= @recipe.created_at.strftime("%B %d, %Y") %></h4>
<p><%= @recipe.description %></p>
<p><em>Prep-time: <%= @recipe.preptime %> min , Cook-time: <%= @recipe.cooktime %> min</em></p>
</div>
<img class="recipe_image"src="<%= @recipe.recipe_image %>">

</div>

<h2>Ingredients</h2>
<hr>
<% @recipe.ingredients.each do |ingredient| %>
<ul>
  <li><%= ingredient %></li>
</ul>
<%end%>

<hr>
<h2>Directions</h2>
<hr>
<p><%= @recipe.direction %></p>


<div class="review_wrapper">
<hr>
<h2>Reviews</h2>
&#8212<%= link_to "Add review", new_dessert_recipe_review_path(@recipe.dessert_id, @recipe) %>&#8212
<hr>



<% @recipe.reviews.each do |review|%>
<p><em><%= review.user.username.upcase %></em> &#8212 <%= review.created_at.strftime("%B %d, %Y @ %-I:%M%p") %> </p>
<p><%= review.body %></p>
<% if review.user == current_user %>
&#8212<%= link_to "Edit review", edit_dessert_recipe_review_path(@recipe.dessert_id, @recipe, review) %>&#8212 &nbsp;
&#8212<%= link_to "Delete review", dessert_recipe_review_path(@recipe.dessert_id, @recipe, review), :method => :delete %>&#8212
<br>
<%else%>
<%end%>
<br>
<hr>
<%end%>
</div>

whisk/app/views/reviews/_form.html.erb
<%= form_for [@dessert, @recipe, @review] do |f| %>

  <%= f.label :comment %>
  <br>
  <%= f.text_area :body, size: "50x5" %>

<br>
  <%= f.submit %>

<% end %>

whisk/app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

whisk/app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

whisk/app/views/reviews/edit.html.erb
<h2>Edit Comment </h2>

<div class="edit-form">
  <%= render "form"  %>
</div>

<%= link_to "Back", root_path  %>

whisk/app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

whisk/app/views/reviews/new.html.erb
<h2>New Comment</h2>

<%= render 'form' %>

whisk/app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

whisk/app/views/reviews/update.html.erb
<h1>Reviews#update</h1>
<p>Find me in app/views/reviews/update.html.erb</p>

whisk/app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

whisk/app/views/users/index.html.erb
<h1>Welcome <%= current_user.username %>! What will you make today?</h1>

<hr>
<h2>Your personal recipes:</h2>
<hr>

<div class="dessert_show_wrapper">
<div class="dessert_show_recipes">
<% @recipe.each do |recipe| %>
<div class="dessert_show_recipe_wrapper">
  <a href="/desserts/<%=recipe.dessert_id%>/recipes/<%=recipe.id%>"><img class="dessert_show_recipe" src="<%= recipe.recipe_image %>"></a>
  <h4><%= link_to recipe.name, dessert_recipe_path(recipe.dessert_id, recipe) %></h4>
</div>
<%end %>
</div>
</div>


<hr>
<h2>Your favorite recipes:</h2>
<hr>
<div class="dessert_show_wrapper">
<div class="dessert_show_recipes">
<% @favorite.each do |favorite| %>
<div class="dessert_show_recipe_wrapper">
  <a href="/desserts/<%=favorite.recipe.dessert_id%>/recipes/<%=favorite.recipe.id%>"><img class="dessert_show_recipe" src="<%= favorite.recipe.recipe_image %>"></a>
  <h4><%= link_to favorite.recipe.name, dessert_recipe_path(favorite.recipe.dessert_id, favorite.recipe)%></h4>
</div>
<%end %>
</div>
</div>

whisk/app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>